# -*- coding: utf-8 -*-
"""Face_detections.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pt4I0IeAYxFor0I6iz5ML9IhDdLBUifq
"""

import numpy as np
import cv2
import matplotlib.pyplot as plt
from google.colab.patches import cv2_imshow

img1 = cv2.imread("/content/image_01.png",cv2.IMREAD_GRAYSCALE)
img2 = cv2.imread("/content/image_02.png",cv2.IMREAD_GRAYSCALE)
img3 = cv2.imread("/content/image_03.png",cv2.IMREAD_GRAYSCALE)

plt.imshow(img1,cmap="gray")

plt.imshow(img2,cmap="gray")

plt.imshow(img3,cmap="gray")

plt.figure(figsize = (18,5))
plt.subplot(131); plt.imshow(img1,cmap="gray"); plt.title("First")
plt.subplot(132); plt.imshow(img2,cmap="gray"); plt.title("Second")
plt.subplot(133); plt.imshow(img3,cmap="gray"); plt.title("Third")

resized1 = cv2.resize(img1, (600, 600))
plt.imshow(resized1 , cmap= "gray")

resized2 = cv2.resize(img2, (600, 600))
plt.imshow(resized2 , cmap= "gray")

resized3 = cv2.resize(img3, (600, 600))
plt.imshow(resized3 , cmap= "gray")

face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")

def detect_face(img):
    face_img=img.copy()
    face_rect=face_cascade.detectMultiScale(face_img)
    for (x,y,w,h) in face_rect:
        cv2.rectangle(face_img,(x,y),(x+w,y+h),(255,255,0),10)
    return face_img

result = detect_face(img1)

plt.imshow(result, cmap="gray")
plt.show()

result1 = detect_face(img2)
plt.imshow(result1,cmap="gray")
plt.show()

result2 = detect_face(img3)
plt.imshow(result2,cmap="gray")
plt.show()

eye_cascade=cv2.CascadeClassifier('haarcascade_eye.xml')

def detect_eye(im):
    face=im.copy()
    rect=eye_cascade.detectMultiScale(face)

    for (x,y,w,h) in rect:
        cv2.rectangle(face,(x,y) , (x+w,y+h) , (127,0,255) , 10)
        cv2_imshow(face)
    return face

result= detect_eye(img1)
plt.imshow(result,cmap='gray')
plt.show()

result= detect_eye(img2)
plt.imshow(result,cmap='gray')
plt.show()

result= detect_eye(img3)
plt.imshow(result,cmap='gray')
plt.show()

# This code block is configured to process a static image for face detection.

# Using the previously successfully loaded image.
image_path = "/content/WIN_20251117_11_34_42_Pro.jpg"

image_to_process = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)

if image_to_process is None:
    print(f"Error: Could not load image from {image_path}. Please ensure the file exists and the path is correct.")
else:
    print(f"Applying face detection to: {image_path.split('/')[-1]}")
    result_with_faces = detect_face(image_to_process)

    # Display the final image with all detected faces:
    plt.imshow(result_with_faces, cmap="gray")
    plt.title(f"Face Detection on {image_path.split('/')[-1]}")
    plt.show()

